name: Build

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    paths:
      - ".github/workflows/build.yml"
      - "main.bicep"
      - "modules/**"

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Validate Template Resources
        uses: Azure/cli@1.0.4
        with:
          inlineScript: |
            az bicep build --file main.bicep --outdir .

