name: Build

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    paths:
      - ".github/workflows/build.yml"
      - "main.bicep"
      - "modules/**"

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Run Bicep Build action
        uses: ./
        with:
          bicepFilePath: ./main.bicep
          outputFilePath: ./azuredeploy.json

      - name: Test action output
        shell: bash
        run: |
          FILE="./azuredeploy.json"
          if test -f "$FILE"; then
            echo "$FILE created successfully"
          else
            echo "$FILE not found."
            exit 1
          fi
